name: Build Release

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          sudo apt update -y
          sudo apt install -y docker golang git
          go install github.com/fyne-io/fyne-cross@latest

          ~/go/bin/fyne-cross linux -arch=amd64,arm64 -app-id="OnionSoup"
          ~/go/bin/fyne-cross windows -arch=amd64,arm64 -app-id="Onion.Soup"

          mv fyne-cross/dist/linux-amd64/onionsoup.tar.xz fyne-cross/onionsoup_linux_amd64.tar.xz
          mv fyne-cross/dist/linux-arm64/onionsoup.tar.xz fyne-cross/onionsoup_linux_arm64.tar.xz
          mv fyne-cross/dist/windows-amd64/onionsoup.tar.xz fyne-cross/onionsoup_windows_amd64.tar.xz
          mv fyne-cross/dist/windows-arm64/onionsoup.tar.xz fyne-cross/onionsoup_windows_arm64.tar.xz

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            LICENSE
            fyne-cross/onionsoup_linux_amd64.tar.xz
            fyne-cross/onionsoup_linux_arm64.tar.xz
            fyne-cross/onionsoup_windows_amd64.exe.zip
            fyne-cross/onionsoup_windows_arm64.exe.zip
          token: ${{ secrets.GH_TOKEN }}
